Fix deployment issue
2026-08-31T12:37:41.35373Z	Run `npm audit` for details.
2026-08-31T12:37:41.419324Z	Executing user command: npm run build
2026-08-31T12:37:41.700433Z
2026-08-31T12:37:41.7009Z	> mermaidflow@0.1.0 build
2026-08-31T12:37:41.701071Z	> tsc --noEmit && vite build
2026-08-31T12:37:41.701208Z
2026-08-31T12:37:45.489138Z	src/features/canvas/services/compactLayout.ts(37,7): error TS6133: 'GRID_PADDING' is declared but its value is never read.
2026-08-31T12:37:45.489968Z	src/features/canvas/services/compactLayout.ts(397,25): error TS2345: Argument of type 'SVGSVGElement | null' is not assignable to parameter of type 'SVGSVGElement'.
2026-08-31T12:37:45.490201Z	  Type 'null' is not assignable to type 'SVGSVGElement'.
2026-08-31T12:37:45.490296Z	src/features/canvas/services/compactLayout.ts(401,27): error TS2345: Argument of type 'SVGSVGElement | null' is not assignable to parameter of type 'SVGSVGElement'.
2026-08-31T12:37:45.490397Z	  Type 'null' is not assignable to type 'SVGSVGElement'.
2026-08-31T12:37:45.541762Z	Failed: Error while executing user command. Exited with error code: 2
2026-08-31T12:37:45.549665Z	Failed: build command exited with code: 1
2026-08-31T12:37:46.16338Z	Failed: error occurred while running build command